#!/usr/bin/env bash
# Reproducible vendor of the pinned Open-Inspect protocol subset (PLAN-04).
# Copies ONLY the pure, Hermes-safe type/model closure consumed by the apps.
# Usage: scripts/vendor-protocol.sh <commit-sha> [upstream-dir]
set -euo pipefail

SHA="${1:?usage: scripts/vendor-protocol.sh <commit-sha> [upstream-dir]}"
UP="${2:-.upstream/background-agents}"
REPO="https://github.com/ColeMurray/background-agents"
DST="packages/protocol/src"
PINF="packages/protocol/PIN"

# --- ensure upstream clone is present and at the requested commit ---
if [ ! -d "$UP/.git" ]; then
  git clone "$REPO" "$UP"
fi
if ! git -C "$UP" cat-file -e "${SHA}^{commit}" 2>/dev/null; then
  git -C "$UP" fetch --unshallow origin 2>/dev/null || git -C "$UP" fetch origin
fi
git -C "$UP" checkout -q "$SHA"
FULL="$(git -C "$UP" rev-parse HEAD)"
S="$UP/packages/shared/src"

mkdir -p "$DST"
rm -f "$DST"/*.ts

# --- copy with a VENDORED provenance header (exact upstream bytes preserved) ---
hdr() { # $1 = dest file, $2 = upstream relpath under packages/shared/src
  {
    printf '// VENDORED from background-agents@%s :: packages/shared/src/%s\n' "$FULL" "$2"
    printf '// Do not edit. Re-vendor via scripts/vendor-protocol.sh. Pinned: packages/protocol/PIN\n'
    cat "$S/$2"
  } > "$1"
}
hdr "$DST/types.ts"               "types/index.ts"
hdr "$DST/integrations.ts"        "types/integrations.ts"
hdr "$DST/triggers-conditions.ts" "triggers/conditions.ts"
hdr "$DST/triggers-types.ts"      "triggers/types.ts"
hdr "$DST/models.ts"              "models.ts"
hdr "$DST/git.ts"                 "git.ts"

# --- flatten the types/ and triggers/ subdirs into a flat src/ (rewrite imports) ---
sed -i.bak 's#from "\.\./triggers/conditions"#from "./triggers-conditions"#' "$DST/types.ts"
sed -i.bak 's#from "\./types"#from "./triggers-types"#'                       "$DST/triggers-conditions.ts"
sed -i.bak -e 's#from "\.\./types"#from "./types"#' \
           -e 's#from "\./conditions"#from "./triggers-conditions"#'          "$DST/triggers-types.ts"
rm -f "$DST"/*.bak

# --- generated barrel (composition, not vendored verbatim) ---
{
  printf '// GENERATED by scripts/vendor-protocol.sh — do not edit. Pinned: packages/protocol/PIN\n'
  printf 'export * from "./types";\n'   # also re-exports ./integrations via its own export *
  printf 'export * from "./models";\n'
  printf 'export * from "./git";\n'
} > "$DST/index.ts"

# --- structured PIN: ref + deployment URL (URL preserved once a real one is set) ---
URL="pending-deploy"
if [ -f "$PINF" ]; then
  EX="$(sed -n 's/^url: //p' "$PINF" 2>/dev/null || true)"
  if [ -n "${EX:-}" ] && [ "$EX" != "pending-deploy" ]; then URL="$EX"; fi
fi
printf 'ref: background-agents@%s\nurl: %s\n' "$FULL" "$URL" > "$PINF"

echo "vendored background-agents@$FULL"
ls -1 "$DST"
